version: "3.2"

services:
  prisma:
    image: prismagraphql/prisma:1.34
    network_mode: "host"
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: 127.0.0.1
            #host: host.docker.internal
            port: 5432
            database: kudoo_dev
            # schema: public
            user: postgres
            password: postgres
            migrations: true
            ssl: false